version: "3.9"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    env_file:
      - devenv/db.env
    volumes:
      - db_data:/home/postgres/pgdata/data
      - ./db/scripts/create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
    # for local development
    network_mode: "host"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "grafita", "-d", "grafitadb"]
      timeout: 40s
      interval: 5s
  app:
    container_name: grafita
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - devenv/grafita.env
      - devenv/db.env
    volumes:
      - ./src:/www/src
    # to connect db on localhost
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: