# Generated by Django 4.1 on 2023-11-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grafita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesgroup',
            name='requested_by',
            field=models.ManyToManyField(related_name='request_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicesgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetypeparameter',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grafita.devicetypeparameter'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
