# Generated by Django 4.1 on 2023-10-20 20:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grafita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafita.devicetype')),
            ],
        ),
    ]
