# Generated by Django 4.1 on 2023-10-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafita', '0002_devicetypeparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
    ]
