# Generated by Django 4.1 on 2023-10-21 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grafita', '0003_remove_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grafita.devicetype'),
        ),
    ]
